<script lang="ts">
</script>

<template>
  <main>
  <button @click="$router.back()" class="button">Back to Application</button>

  <div class="content">
    <h1>Privacy Policy</h1>
    <h3>Contact</h3>
    <p>bdqb (at) s-blu.de</p>
    <div>
      <h2>Personal data storage and processing</h2>
      <p>
        Collection and processing of your personal information is carried out in accordance with the laws of the European Union and Germany.
        We are collecting data to provide our services as well for statistical purposes.
      </p>
      <h2>Data storage, alteration, and removal</h2>
      <p>
        All data you input into https://s-blu.github.io/basic-dataview-query-builder/ via input fields or similar is stored locally on the user client side alone and is not transmitted to the server in any way.
      </p>
      <h2>Processing of visiting technical data</h2>
      <p>
        Records of your IP address, time of visit, browser settings, operational system and other technical information
        is saved in the database when you visit https://s-blu.github.io/basic-dataview-query-builder/. This data is necessary for the correct display of the
        website’s content. It is impossible to identify the person of the visitor using this data.
      </p>
      <h2>Processing of data for analytics (Matomo)</h2>
      <p>
        https://s-blu.github.io/basic-dataview-query-builder/ uses Matomo Analytics for statistical purposes, to improve our site and to recognize and stop any
        misuse. When you visit our site, we will store: 
        <ul>
          <li>Your anonymised IP address (anonymised by 2 bytes)</li>
          <li>Date and time of the request</li>
          <li>Title of the page being viewed (Page Title)</li>
          <li>URL of the page being viewed (Page URL)</li>
          <li>URL of the page that was viewed prior to the current page (Referrer URL)</li>
          <li>Screen resolution being used</li>
          <li>Time in your timezone</li>
          <li>Links to an outside domain that were clicked</li>
          <li>Pages generation time (the time it takes for webpages to be generated by the webserver and then downloaded by the user: <a href="https://matomo.org/docs/page-speed/">Page speed</a>)</li>
          <li>Location of the user: country, region, city, approximate latitude and longitude (<a href="https://matomo.org/docs/geo-locate/">Geolocation</a>)</li>
          <li>Main Language of the browser being used (<code>Accept-Language</code> header)</li>
          <li>User Agent of the browser being used (<code>User-Agent</code> header)</li>
        </ul>
      </p>
      <h2>Cookies processing</h2>
      <p>
        https://s-blu.github.io/basic-dataview-query-builder/ does not use any cookies.
      </p> 
      <h2>Processing of personal data by other services</h2>
      <p>
        This website is hosted on Github Pages, which is part of Github. Please refer to Githubs Privacy Policy for more
        information: https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-privacy-statement
      </p>
      <p>
        Data collected by these services may be provided to other services within those organizations. They can use the
        data for advertising personalization of their own advertising network. You can learn about user agreements of
        those organizations on their websites. You can also refuse their collection of your personal data. We do not
        pass any personal data to other organizations or services, which are not listed in this privacy policy. As an
        exception, the collected data may be provided on a lawful request of state authorities, that are authorized to
        request such information.
      </p>
      <h2>Links to other websites</h2>
      <p>
        Our website https://s-blu.github.io/basic-dataview-query-builder/ may contain links to other websites, which are not under our control. We are not
        responsible for the content of these websites. We recommend you familiarize yourself with the privacy policy of
        every website that you visit, if such policy exists.
      </p>
      <h2>Changes to the privacy policy</h2>
      <p>
        From time to time, our website https://s-blu.github.io/basic-dataview-query-builder/ may update our privacy policy. We inform about any changes to the
        privacy policy, placed on this webpage. We are monitoring any changes in legislation, which is related to
        personal data in European Union and Germany. If you have entered any of your personal data on our website, we
        will inform you about the changes in our privacy policy. If your personal data, and more specifically, your
        contact information was not entered or entered incorrectly, we will not be able to contact you.
      </p>
      <h2>Feedback and final clauses</h2>
      <p>
        You can contact the administration of https://s-blu.github.io/basic-dataview-query-builder/ regarding any questions related to privacy policy on:
        bdqb-privacy@s-blu.de. If you
        do not agree with this privacy policy, you cannot use this services. In this case you should
        avoid visiting our website.
      </p>
      <p class="generator-hint">
        <em
          >This document was produced using
          <a href="https://profiset.org/free-customizable-privacy-policy-online-generator-gdpr/"
            >privacy policy online generator Profiset.org</a
          ></em
        >
      </p>
    </div>
  </div></main>
</template>

<style scoped lang="scss">
.generator-hint {
  font-size: 8pt;
}

.content {
  color: var(--color-text)
}

.button {
  margin-bottom: 1em;
}
</style>